services:
  nagios:
    image: jasonrivers/nagios
    container_name: nagios-server
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./servers:/opt/nagios/etc/servers
    networks:
      - ansible_ansible-net

networks:
  ansible_ansible-net:
    external: true


