---
- name: Complete Ansible Demo (Ping + Django Deploy)
  hosts: all
  become: yes

  tasks:

    - name: Ping nodes
      ping:

    - name: Create test file
      file:
        path: /tmp/ansible_test.txt
        state: touch

    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present
        update_cache: yes

    - name: Clone Stock Market app
      git:
        repo: "https://github.com/nitishchy12/Stock-Market-Place.git"
        dest: /home/ansible/app
        force: yes

    - name: Install Python packages
      pip:
        requirements: /home/ansible/app/requirements.txt

    - name: Run migrations
      command: python3 manage.py migrate
      args:
        chdir: /home/ansible/app

    - name: Start Django server
      shell: nohup python3 manage.py runserver 0.0.0.0:8000 &
      args:
        chdir: /home/ansible/app
